### PR TITLE
fix: tests fails because of a buffer related issue

### PR DESCRIPTION
**Pull request by jonaslagoni**

### CODE REVIEW

**Comment by jonaslagoni** [comment]
I fixed the small issue regarding the nats.ts library being a buffere where I assumed it wasent making the tests fail "randomly"

**Comment by derberg** [comment]
small fix, 42 files changed

**Review by derberg — APPROVED** [review]

**Comment by jonaslagoni** [comment]
🤔 @derberg why is it 0.1.0 xD?

**Comment by derberg** [comment]
because this is what you set in package.json and the previous one was 0.0.1. What did you expect? I guess 0.1.1? but semantic-release did not find 0.1.0 on npm because of the previous failure, so it had still `feat` commit on its list. Does it make sense?

**Comment by jonaslagoni** [comment]
Ahhh yea, I mixed this release with another thats why it was confusing... Sorry for the ping 😄

**Pull request merged**
